@localurl = http://localhost:6002
@resourceId = 00000000-0000-0000-0000-000000000014
@tags = ["vehicles", "armors"]

###
POST {{localurl}}/resources/
Content-Type: application/json

{
    "resourceId": "{{resourceId}}",
    "tags": {{tags}}
}

###
###
GET {{localurl}}/resources/{{resourceId}}
###

###
POST {{localurl}}/resources/{{resourceId}}/reserve-resource
Content-Type: application/json

{
    "resourceId": "{{resourceId}}",
    "from": "08/26/2020",
    "to": "08/27/2020",
    "priority": 1
}
###
